from datetime import date, datetime
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field


class TodoBase(BaseModel):
    title: str
    description: str | None = None
    completed: bool = False
    priority: Literal["low", "medium", "high"] = "medium"
    due_date: date | None = None


class TodoCreate(TodoBase):
    pass


class TodoUpdate(TodoBase):
    pass


class Todo(TodoBase):
    model_config = ConfigDict(from_attributes=True)

    id: int
    created_at: datetime
    updated_at: datetime | None = None


class TodoPatch(BaseModel):
    title: str | None = None
    description: str | None = None
    completed: bool | None = None
    priority: Literal["low", "medium", "high"] | None = None
    due_date: date | None = None


ANONYMOUS_ID_PATTERN = r"^[A-Za-z0-9][A-Za-z0-9._:-]{7,127}$"


class VisitRequest(BaseModel):
    visitor_id: str = Field(
        min_length=8,
        max_length=128,
        pattern=ANONYMOUS_ID_PATTERN,
        description="Anonymous stable browser identifier generated by the frontend.",
    )


class VisitResponse(BaseModel):
    total_visitors: int


class HeartbeatRequest(BaseModel):
    session_id: str = Field(
        min_length=8,
        max_length=128,
        pattern=ANONYMOUS_ID_PATTERN,
        description="Anonymous random session identifier generated for this page load.",
    )
    song_id: int = Field(ge=1, le=30)


class HeartbeatResponse(BaseModel):
    active_listeners: int


class PlayRequest(BaseModel):
    song_id: int = Field(ge=1, le=30)
    session_id: str = Field(
        min_length=8,
        max_length=128,
        pattern=ANONYMOUS_ID_PATTERN,
        description="Anonymous random session identifier generated for this page load.",
    )


class PlayResponse(BaseModel):
    song_id: int
    plays: int


class AnalyticsStatsResponse(BaseModel):
    total_visitors: int
    active_listeners: int
    total_plays: int


class SongStatsResponse(BaseModel):
    song_id: int
    title: str
    artist: str
    plays: int

